//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeGithubPortfolio.Site.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controllers_HomeController_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_HomeController_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwesomeGithubPortfolio.Site.Resources.Controllers.HomeController.en-US", typeof(Controllers_HomeController_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong experience in building scalable and secure APIs, microservices, and backend architectures for cloud and on-premise environments.
        /// </summary>
        internal static string CategoryBackend {
            get {
                return ResourceManager.GetString("CategoryBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience in designing and managing relational and NoSQL databases, ensuring efficient data storage and retrieval.
        /// </summary>
        internal static string CategoryDBA {
            get {
                return ResourceManager.GetString("CategoryDBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficient in infrastructure automation, CI/CD pipelines, containerization, and cloud-native solutions to optimize deployment and scalability.
        /// </summary>
        internal static string CategoryDevops {
            get {
                return ResourceManager.GetString("CategoryDevops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise in designing and developing responsive, high-performance web applications with modern UI frameworks.
        /// </summary>
        internal static string CategoryFrontend {
            get {
                return ResourceManager.GetString("CategoryFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled in scripting and automation for server management, system monitoring, and performance optimization.
        /// </summary>
        internal static string CategoryInfra {
            get {
                return ResourceManager.GetString("CategoryInfra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge in developing cross-platform and native mobile applications with a focus on performance and usability.
        /// </summary>
        internal static string CategoryMobile {
            get {
                return ResourceManager.GetString("CategoryMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Contribution.
        /// </summary>
        internal static string FirstContribution {
            get {
                return ResourceManager.GetString("FirstContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m quite famous in my neighborhood.
        /// </summary>
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dev&apos;s who rely on my work.
        /// </summary>
        internal static string FollowersMessage {
            get {
                return ResourceManager.GetString("FollowersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My work in numbers.
        /// </summary>
        internal static string MeInNumbersTitle {
            get {
                return ResourceManager.GetString("MeInNumbersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More on my projects.
        /// </summary>
        internal static string MoreWork {
            get {
                return ResourceManager.GetString("MoreWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handcrafted.
        /// </summary>
        internal static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects I&apos;ve been envolved.
        /// </summary>
        internal static string ProjectsTitle {
            get {
                return ResourceManager.GetString("ProjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What I Do..
        /// </summary>
        internal static string ServicesWhatIDo {
            get {
                return ResourceManager.GetString("ServicesWhatIDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since {0} building industry top quality software.
        /// </summary>
        internal static string StartDate_0 {
            get {
                return ResourceManager.GetString("StartDate-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years of experience building the world.
        /// </summary>
        internal static string StartDate_1 {
            get {
                return ResourceManager.GetString("StartDate-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry-leading.
        /// </summary>
        internal static string WellKnowProjects {
            get {
                return ResourceManager.GetString("WellKnowProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
