name: MASTER - Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  tag-generation:
    name: TAG Generation
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: [ tag-generation ]
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/AwesomeGithubPortfolio.Site/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "ghcr.io/brunobritodev/awesome-github-portfolio:${{ needs.tag-generation.outputs.tag }}"
            "ghcr.io/brunobritodev/awesome-github-portfolio:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: Release - Generate Changelog & Tag
    runs-on: ubuntu-latest
    needs: [ docker ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}